### ISSUE TITLE
Config initialiser is inaccessible

### ISSUE THREAD

**Issue by wow-such-amazing** [shima11/FlexiblePageControl#13]
Thanks for the library!
The initialiser for `Config` structure is not available. Because it is not defined as public. 
![2018-06-25 11 30 04](https://user-images.githubusercontent.com/7022709/41842465-29a8f290-786b-11e8-8322-d6b32296fc55.png)
The solution is to write like this:
```
    // MARK: public

    public struct Config {

        public var displayCount: Int
        public var dotSize: CGFloat
        public var dotSpace: CGFloat
        public var smallDotSizeRatio: CGFloat
        public var mediumDotSizeRatio: CGFloat
        
        public init(displayCount: Int = 7,
                    dotSize: CGFloat = 6.0,
                    dotSpace: CGFloat = 4.0,
                    smallDotSizeRatio: CGFloat = 0.5,
                    mediumDotSizeRatio: CGFloat = 0.7) {
            self.displayCount = displayCount
            self.dotSize = dotSize
            self.dotSpace = dotSpace
            self.smallDotSizeRatio = smallDotSizeRatio
            self.mediumDotSizeRatio = mediumDotSizeRatio
        }
    }

    // default config

    private var config = Config()
```
This way you can also specify default values right in the initialiser. So users of the library will be able to override only properties, that they need to override 🙂

**Comment by wow-such-amazing** [comment]
I created PR to fix this issue 👍 
https://github.com/shima11/FlexiblePageControl/pull/14

**Comment by shima11** [comment]
@crabman448  Thank you for your Issue and PR.

I got it, merge pull request 👍

**Comment by Chetan9007** [comment]
@shima11 
 The same issue while using the Carthage, please update it. :)
