### ISSUE TITLE
Views reusing

### ISSUE THREAD

**Issue by serejahh** [shima11/FlexiblePageControl#2]
Hey! Thanks for the awesome lib. Do you have any plans to add views reusing? In my app I can add up to 100 photos in a roll and performance may be low because of 100 views

**Comment by shima11** [comment]
Thank you for your comment!
For now, I have not plans to add views reusing. I may do it if I have time.

**Comment by shima11** [comment]
@serejahh 
I corresponded to this issue. I think that 100 pages will be OK.
