### ISSUE TITLE
intrinsicContentSize is not updated if the numberOfPages is changed

### ISSUE THREAD

**Issue by mime29** [shima11/FlexiblePageControl#21]
I use it in a cell and the component width is not updated when I update the numberOfPages.
The result being that the dots are not centered in the view anymore.

An easy fix is to force the intrinsicContentSize to be updated and call https://developer.apple.com/documentation/uikit/uiview/1622457-invalidateintrinsiccontentsize

**Comment by shima11** [comment]
Thank you for your information!

**Comment by shima11** [comment]
As we updated in 1.0.8, please use that.

**Comment by mime29** [comment]
ok, I will !

**Comment by mime29** [comment]
It's working well now!
Thank you Shima-san

You can close this issue now
