### ISSUE TITLE
Swiping twice or more creates issues

### ISSUE THREAD

**Issue by s2imon** [shima11/FlexiblePageControl#5]
Hey there, love it, just added it today. While testing I found an issue, which I thought I might mention here. While swiping before the item has stopped decelerating it seems to jump and confuse the library. 
Is this something you're reproducing or might it be my problem?

<img width="124" alt="glass" src="https://cloud.githubusercontent.com/assets/1027012/26267366/00863c50-3cea-11e7-8430-502339013b9a.png">

(normal view below)

<img width="124" alt="glass 2" src="https://cloud.githubusercontent.com/assets/1027012/26267395/21d10714-3cea-11e7-8c68-3609a1063fca.png">

Thanks!

**Comment by shima11** [comment]
@s2imon 
Thank you for your comment.

I do not know if it solves it, please try it with the latest version (tag 1.0.5).
Or, There may be a bug if displayCount is small.

**Comment by s2imon** [comment]
Thanks @shima11 ! Display count is 7, yes - updated and it seems to work slightly better but still not fixing it. Thanks for taking note :)

Simon
