### ISSUE TITLE
Add storyboard support.

### ISSUE THREAD

**Issue by HyunjoonKo** [shima11/FlexiblePageControl#6]
I get the following error when using Storyboard.

`fatal error: init(coder:) has not been implemented: file ... /Pods/FlexiblePageControl/FlexiblePageControl/FlexiblePageControl.swift, line 98`

So, I fixed the error function as follows.

```swift
required public init?(coder aDecoder: NSCoder) {
        //fatalError("init(coder:) has not been implemented")
        super.init(coder: aDecoder)

        setup()
        updateViewSize()
}
```

This works well on the Storyboard. Could you put this code in it?

**Comment by shima11** [comment]
@HyunjoonKo 
Thank you for your comment.

I’m sorry for this belated reply.
Supported storyboard.
